apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: nginx-prod
  namespace: nginx
  annotations:
    kargo.akuity.io/argocd-context: '[{"name":"nginx-prod","namespace":"argocd"}]'
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: nginx
      sources:
        stages:
          - nginx-staging
  promotionTemplate:
    spec:
      steps:
        - uses: argocd-update
          config:
            apps:
              - name: nginx-prod
                namespace: argocd
                sources:
                  - repoURL: https://github.com/jiachengxu/mcp-test-repo.git
                    kustomize:
                      images:
                        - repoURL: mirror.gcr.io/library/nginx
                          tag: '${{ imageFrom("mirror.gcr.io/library/nginx").Tag }}'
