apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nginx-staging
commonLabels:
  app.kubernetes.io/instance: nginx-staging
  env: staging
resources:
  - ../../base
images:
  - name: polinux/stress
    newTag: latest
